### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by dvdcastro** [twz123/rerun-pr-workflows-action#93]
Hello, this project looks nice.

How do I use it? Do you have a tutorial or some hints?

Thanks!

**Comment by twz123** [comment]
I came up with this when coding on another project that maintained a bespoke set of scripts via actions/github-script to accomplish similar things. Those scripts were a bit hard to maintain, given that there was no real IDE support, not to mention unit tests. I thought it would be nice to have it as a reusable action, as a real project. I never came along to reintegrate it back, and now this action is basically just used by itself, and I never wrote a README snippet on how to use it.

That being said, considering the limitations mentioned in the README, I think it is functional. Have a look at the "[Re-run workflows for incoming PRs][trigger-wf]" workflow defined in [trigger.yaml]. This is how it invokes itself, and triggers the "[CI][ci-wf]" workflow defined in [ci.yaml]. The workflow to be triggered is to be specified via the `workflow` key in the action's `with` block.

So, without having tested this, something like the following should be working for other projects:

```yaml
name: Re-run workflows for incoming PRs

on:
  push:
    branches:
    - '**'

jobs:
  trigger_some_other_workflow:
    name: Trigger some other workflow
    runs-on: ubuntu-20.04
    steps:
    - name: Trigger some other workflow
      uses: twz123/rerun-pr-workflows-action@v0.2
      with:
        workflow: Some other workflow
```

Would be nice to add this to the README! Interested in doing a PR? :smiley:

[trigger-wf]: https://github.com/twz123/rerun-pr-workflows-action/actions/workflows/trigger.yaml
[trigger.yaml]: https://github.com/twz123/rerun-pr-workflows-action/blob/17767e16b93dced9cb720d9a536744ad3e879ac0/.github/workflows/trigger.yaml
[ci-wf]: https://github.com/twz123/rerun-pr-workflows-action/actions/workflows/ci.yaml
[ci.yaml]: https://github.com/twz123/rerun-pr-workflows-action/blob/17767e16b93dced9cb720d9a536744ad3e879ac0/.github/workflows/ci.yaml
